"""
agent/memory.py
===============
Dual-layer persistent memory for the Doomscroll Agent.

Why two layers?
---------------
Different access patterns need different storage primitives:

  Layer 1: JSONL log  (data/posts_log.jsonl)
  -------------------------------------------
  - Append-only, one JSON object per line, human-readable
  - Zero dependencies beyond Python's stdlib
  - Use for: full history replay, debugging, CSV export, deduplication by post_id
  - Limitation: O(n) scan for every query — acceptable up to ~500K posts per file

  Layer 2: ChromaDB vector store  (data/chroma/)
  ------------------------------------------------
  - Local, persistent, embedded — no server process required
  - Embeddings generated by sentence-transformers (all-MiniLM-L6-v2, 384-dim)
    running entirely on CPU — no GPU, no cloud API call, no cost per embedding
  - Use for: semantic similarity search, topic clustering, dedup at scale
  - Limitation: not suitable for production scale beyond ~1M embeddings on a
    single machine; at that point, migrate to Qdrant or Pinecone

Both layers are kept consistent: every store() call writes to both.
The vector store degrades gracefully to a no-op if chromadb or
sentence-transformers are not installed (the JSONL log always works).

Data directory layout
---------------------
  data/
    posts_log.jsonl       one JSON object per scraped post
    insights_log.jsonl    one JSON object per pipeline run's corpus insight
    chroma/               ChromaDB persistent storage directory
    agent.log             Python logging output (written by main.py)

Author : Marc Lapira
Project: Doomscroll Agent — Binox 2026 Take-Home (G2)
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import os

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configurable paths
# ---------------------------------------------------------------------------

# DATA_DIR can be overridden via environment variable for Docker deployments
# where /app/data is mounted as a persistent volume.
DATA_DIR      = Path(os.environ.get("DATA_DIR", "data"))
LOG_FILE      = DATA_DIR / "posts_log.jsonl"
CHROMA_DIR    = DATA_DIR / "chroma"
INSIGHTS_LOG  = DATA_DIR / "insights_log.jsonl"


def _ensure_dirs() -> None:
    """Create the data directory tree if it doesn't exist yet."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    CHROMA_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Lazy-loaded optional heavy dependencies
# ---------------------------------------------------------------------------

# These module-level globals are None until the first store/search call.
# Using lazy initialisation avoids paying the startup cost (~2-3 s for
# sentence-transformers model load) when the CLI flags like --stats or
# --search are used without a full pipeline run.
_chroma_client = None
_collection    = None
_embedder      = None


def _get_embedder():
    """
    Return a SentenceTransformer model, loading it on first call.

    Model choice: all-MiniLM-L6-v2
    - 384-dimensional embeddings (compact, fast cosine similarity)
    - ~80 MB on disk
    - Runs on CPU in ~50 ms/sentence — fast enough for batches of 25 posts
    - Strong enough for topic-level semantic grouping (not fine-grained NLI)

    Returns None if sentence-transformers is not installed, allowing the
    pipeline to run in JSON-log-only mode.
    """
    global _embedder
    if _embedder is None:
        try:
            from sentence_transformers import SentenceTransformer
            _embedder = SentenceTransformer("all-MiniLM-L6-v2")
            logger.info("Loaded embedding model: all-MiniLM-L6-v2")
        except (ImportError, Exception) as exc:
            logger.warning(
                "sentence-transformers unavailable (%s); "
                "vector store disabled — falling back to JSON-log-only mode.",
                exc,
            )
    return _embedder


def _get_collection():
    """
    Return the ChromaDB collection, creating it on first call.

    Collection schema:
    - id        : Reddit post_id (deduplication key)
    - embedding : 384-dim float vector from all-MiniLM-L6-v2
    - document  : post.full_text() substring (first 2048 chars)
    - metadata  : flat dict of scalar fields (subreddit, sentiment, score, etc.)

    Using cosine distance (hnsw:space="cosine") because we care about semantic
    direction, not vector magnitude — two posts about the same topic should be
    close regardless of text length.

    Returns None if chromadb is not installed.
    """
    global _chroma_client, _collection
    if _collection is not None:
        return _collection
    try:
        import chromadb
        # PersistentClient stores everything on disk — survives process restarts
        _chroma_client = chromadb.PersistentClient(path=str(CHROMA_DIR))
        _collection = _chroma_client.get_or_create_collection(
            name     = "doomscroll_posts",
            metadata = {"hnsw:space": "cosine"},    # cosine similarity metric
        )
        logger.info(
            "ChromaDB collection ready — %d existing embeddings",
            _collection.count(),
        )
    except (ImportError, Exception) as exc:
        logger.warning("chromadb unavailable (%s); vector store disabled.", exc)
    return _collection


# ---------------------------------------------------------------------------
# Late import of Post to avoid circular imports
# (memory imports from scraper; scraper must not import from memory)
# ---------------------------------------------------------------------------
from agent.scraper import Post  # noqa: E402


# ---------------------------------------------------------------------------
# Core public operations
# ---------------------------------------------------------------------------

def store(posts: list[Post]) -> int:
    """
    Persist a list of Posts to both storage layers.

    Deduplication is performed against the JSONL log before any writes.
    A post is considered duplicate if its post_id already appears in the log.
    Only new posts are written, so calling store() with the same batch twice
    is safe and idempotent.

    Parameters
    ----------
    posts : list of Post objects (may have sentiment/topics set or not)

    Returns
    -------
    int : number of *new* posts actually written to storage
    """
    _ensure_dirs()

    # Load all existing post IDs from the JSONL log for deduplication.
    # This is an O(n) scan on every call, which is fine up to ~500K posts.
    # Beyond that, maintain an in-memory set as a module-level cache.
    existing_ids = _load_existing_ids()
    new_posts    = [p for p in posts if p.post_id not in existing_ids]

    if not new_posts:
        logger.info(
            "All %d posts already in store — nothing to write", len(posts)
        )
        return 0

    # ------------------------------------------------------------------
    # Layer 1: JSONL log
    # Append mode ("a") is safe for concurrent writers on Linux (POSIX
    # append semantics are atomic per-line for records under ~512 bytes).
    # On Windows, use a file lock if concurrent writers are possible.
    # ------------------------------------------------------------------
    with LOG_FILE.open("a", encoding="utf-8") as f:
        for p in new_posts:
            # json.dumps with ensure_ascii=False to preserve Unicode in post bodies
            f.write(json.dumps(p.to_dict(), ensure_ascii=False) + "\n")

    logger.info(
        "Appended %d new posts to %s", len(new_posts), LOG_FILE
    )

    # ------------------------------------------------------------------
    # Layer 2: ChromaDB vector store (skipped if deps are unavailable)
    # ------------------------------------------------------------------
    embedder   = _get_embedder()
    collection = _get_collection()

    if embedder and collection:
        # Build parallel lists for ChromaDB's batch-insert API
        texts     = [p.full_text()[:2048] for p in new_posts]  # cap to avoid OOM
        ids       = [p.post_id for p in new_posts]
        metadatas = [
            {
                # All metadata values must be scalar (str/int/float) for ChromaDB
                "subreddit":    p.subreddit,
                "title":        p.title[:512],          # cap for metadata field limits
                "sentiment":    p.sentiment or "unknown",
                "score":        p.score,
                "created_utc":  p.created_utc.isoformat(),
                "fetched_at":   p.fetched_at.isoformat(),
                # topics list is serialised as comma-separated string (ChromaDB
                # doesn't support list metadata values)
                "topics":       ",".join(p.topics),
                "url":          p.url,
            }
            for p in new_posts
        ]

        # encode() returns a numpy array; .tolist() converts to plain Python lists
        # that ChromaDB's REST-serialisation layer expects
        embeddings = embedder.encode(texts, show_progress_bar=False).tolist()

        collection.add(
            ids        = ids,
            embeddings = embeddings,
            documents  = texts,
            metadatas  = metadatas,
        )
        logger.info(
            "Inserted %d embeddings into ChromaDB (%d total)",
            len(new_posts), collection.count(),
        )

    return len(new_posts)


def store_insight(insight: dict[str, Any], subreddits: list[str]) -> None:
    """
    Append a corpus-level insight snapshot to the insights log.

    Each entry captures the full insight dict alongside the subreddits
    monitored and an ISO-8601 timestamp. This log feeds the trend delta
    comparison on subsequent pipeline runs.

    The insights log is intentionally separate from the posts log so that
    insight records can be queried, exported, or visualised independently.
    """
    _ensure_dirs()
    record = {
        "timestamp":  datetime.now(timezone.utc).isoformat(),
        "subreddits": subreddits,
        "insight":    insight,
    }
    with INSIGHTS_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

    logger.info("Insight snapshot persisted to %s", INSIGHTS_LOG)


def load_posts(
    subreddit: str | None = None,
    since: datetime | None = None,
    limit: int = 200,
) -> list[Post]:
    """
    Load posts from the JSONL log, with optional filtering.

    Parameters
    ----------
    subreddit : if set, only return posts from this subreddit
    since     : if set, only return posts created after this datetime
    limit     : maximum number of posts to return (most recent first)

    Returns
    -------
    list[Post] sorted by created_utc descending, capped at `limit`.

    Note: this function reads the entire log file on every call (O(n) scan).
    For high-frequency queries, consider maintaining an in-memory post cache
    keyed by post_id, or adding an SQLite index layer.
    """
    _ensure_dirs()
    if not LOG_FILE.exists():
        return []

    posts: list[Post] = []
    with LOG_FILE.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue    # skip blank lines (e.g. trailing newline)

            try:
                d = json.loads(line)
            except json.JSONDecodeError as exc:
                # Corrupt line (e.g. partial write on crash) — skip and continue
                logger.warning("Skipping corrupt JSONL line: %s", exc)
                continue

            # Apply filters
            if subreddit and d.get("subreddit") != subreddit:
                continue

            created = datetime.fromisoformat(d["created_utc"])
            if since and created < since:
                continue

            # Reconstruct a Post dataclass from the stored dict
            p = Post(
                post_id      = d["post_id"],
                platform     = d.get("platform", "reddit"),
                subreddit    = d["subreddit"],
                title        = d["title"],
                body         = d.get("body", ""),
                author       = d.get("author", ""),
                url          = d.get("url", ""),
                score        = d.get("score", 0),
                num_comments = d.get("num_comments", 0),
                created_utc  = created,
                flair        = d.get("flair"),
                top_comments = d.get("top_comments", []),
                sentiment    = d.get("sentiment"),
                topics       = d.get("topics", []),
                summary      = d.get("summary"),
            )
            posts.append(p)

    # Sort most-recent first, then cap at limit
    posts.sort(key=lambda p: p.created_utc, reverse=True)
    return posts[:limit]


def semantic_search(query: str, n_results: int = 10) -> list[dict]:
    """
    Find the most semantically similar posts to `query` using vector search.

    The query is embedded using the same model as the stored posts, then a
    cosine-similarity nearest-neighbour search is run against the ChromaDB
    collection. Results are returned with their distance score (0 = identical,
    2 = maximally dissimilar in cosine space).

    Falls back to an empty list if ChromaDB or sentence-transformers are
    unavailable — the caller should handle this gracefully.

    Parameters
    ----------
    query     : natural-language search string
    n_results : maximum number of results to return

    Returns
    -------
    list of dicts, each containing metadata fields + document_snippet + distance
    """
    embedder   = _get_embedder()
    collection = _get_collection()

    if not embedder or not collection:
        logger.warning("Vector search unavailable — returning empty results")
        return []

    if collection.count() == 0:
        logger.warning("ChromaDB collection is empty — no posts to search")
        return []

    # Embed the query into the same vector space as our stored posts
    query_vector = embedder.encode([query]).tolist()

    results = collection.query(
        query_embeddings = query_vector,
        # Cap n_results at the number of stored documents to avoid ChromaDB errors
        n_results        = min(n_results, collection.count()),
        include          = ["metadatas", "documents", "distances"],
    )

    # Flatten ChromaDB's nested result structure into a flat list of dicts
    output = []
    for i, meta in enumerate(results["metadatas"][0]):
        output.append({
            **meta,
            # Truncated snippet for display purposes (full document is in ChromaDB)
            "document_snippet": results["documents"][0][i][:300],
            # Lower distance = higher similarity; 0.0 = identical vector
            "distance": results["distances"][0][i],
        })

    return output


def load_latest_insight() -> dict | None:
    """
    Return the most recent insight snapshot from the insights log, or None.

    Used by pipeline.py to fetch the "previous" snapshot for trend delta
    comparison. Reads only the last non-empty line of the file, which is
    efficient for append-only logs.
    """
    if not INSIGHTS_LOG.exists():
        return None

    last_line = None
    with INSIGHTS_LOG.open(encoding="utf-8") as f:
        for line in f:
            if line.strip():
                last_line = line.strip()   # keep advancing — we want the last one

    if last_line:
        try:
            return json.loads(last_line)
        except json.JSONDecodeError as exc:
            logger.warning("Could not parse last insight snapshot: %s", exc)
            return None

    return None


def stats() -> dict[str, Any]:
    """
    Return basic statistics about the memory store for display in --stats mode.

    Counts are derived by scanning the log files (not cached), so this
    reflects the actual on-disk state at call time.
    """
    _ensure_dirs()

    # Count lines in the posts log
    total_posts = 0
    if LOG_FILE.exists():
        with LOG_FILE.open(encoding="utf-8") as f:
            total_posts = sum(1 for line in f if line.strip())

    # Count lines in the insights log
    insight_count = 0
    if INSIGHTS_LOG.exists():
        with INSIGHTS_LOG.open(encoding="utf-8") as f:
            insight_count = sum(1 for line in f if line.strip())

    # ChromaDB count (may be None if not installed)
    collection   = _get_collection()
    chroma_count = collection.count() if collection else 0

    return {
        "json_log_posts":    total_posts,
        "chroma_embeddings": chroma_count,
        "insight_snapshots": insight_count,
        "log_path":          str(LOG_FILE.resolve()),
        "chroma_path":       str(CHROMA_DIR.resolve()),
    }


# ---------------------------------------------------------------------------
# Internal helpers (not part of the public API)
# ---------------------------------------------------------------------------

def _load_existing_ids() -> set[str]:
    """
    Load the set of all post_ids already persisted in the JSONL log.

    Used by store() for deduplication. Scans the log linearly — ~5 ms
    for 10K posts on an SSD, which is negligible at our run cadence.
    """
    if not LOG_FILE.exists():
        return set()

    ids: set[str] = set()
    with LOG_FILE.open(encoding="utf-8") as f:
        for line in f:
            try:
                ids.add(json.loads(line)["post_id"])
            except (json.JSONDecodeError, KeyError):
                pass    # skip corrupt lines silently

    return ids
